# Site settings
title: Bryce Benson
email: bryce.e.benson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bryce Benson - Front End Developer - A responsive portfolio site showcasing some of my work.
baseurl: "" # the subpath of your site, e.g. /blog/
host: 0.0.0.0
permalink: /:title.html
excerpt_separator: <!--readmore-->
url: "http://brycebenson.com" # the base hostname & protocol for your site
twitter_username: ceryb
github_username:  brycebenson

# Build settings
markdown: kramdown
